language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
install:
  # protobuf 3.6.1 or later is necessary
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip -d protoc3
  - export PATH=$PATH:$PWD/protoc3/bin/
  - sudo apt-get install -qq libsnappy-dev
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - make
  - pytest --cov=keynote_parser
