# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkSinusoidImageSourcePython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkSinusoidImageSourcePython', [dirname(__file__)])
        except ImportError:
            import _itkSinusoidImageSourcePython
            return _itkSinusoidImageSourcePython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkSinusoidImageSourcePython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkSinusoidImageSourcePython = swig_import_helper()
    del swig_import_helper
else:
    import _itkSinusoidImageSourcePython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkParametricImageSourcePython
import itkArrayPython
import vnl_vectorPython
import stdcomplexPython
import pyBasePython
import vnl_matrixPython
import itkGenerateImageSourcePython
import itkImagePython
import itkCovariantVectorPython
import itkVectorPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkRGBPixelPython
import itkImageRegionPython
import itkIndexPython
import itkOffsetPython
import itkSizePython
import ITKCommonBasePython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkPointPython
import itkSymmetricSecondRankTensorPython
import itkRGBAPixelPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkVectorImagePython
import itkVariableLengthVectorPython

def itkSinusoidImageSourceIF3_New():
  return itkSinusoidImageSourceIF3.New()


def itkSinusoidImageSourceIF2_New():
  return itkSinusoidImageSourceIF2.New()

class itkSinusoidImageSourceIF2(itkParametricImageSourcePython.itkParametricImageSourceIF2):
    """Proxy of C++ itkSinusoidImageSourceIF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkSinusoidImageSourceIF2_Pointer"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkSinusoidImageSourceIF2 self) -> itkSinusoidImageSourceIF2_Pointer"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_Clone(self)


    def SetPhaseOffset(self, _arg):
        """SetPhaseOffset(itkSinusoidImageSourceIF2 self, double const _arg)"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_SetPhaseOffset(self, _arg)


    def GetPhaseOffset(self):
        """GetPhaseOffset(itkSinusoidImageSourceIF2 self) -> double"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_GetPhaseOffset(self)


    def SetFrequency(self, _arg):
        """SetFrequency(itkSinusoidImageSourceIF2 self, itkFixedArrayD2 _arg)"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_SetFrequency(self, _arg)


    def GetFrequency(self):
        """GetFrequency(itkSinusoidImageSourceIF2 self) -> itkFixedArrayD2"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_GetFrequency(self)

    __swig_destroy__ = _itkSinusoidImageSourcePython.delete_itkSinusoidImageSourceIF2

    def cast(obj):
        """cast(itkLightObject obj) -> itkSinusoidImageSourceIF2"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkSinusoidImageSourceIF2

        Create a new object of the class itkSinusoidImageSourceIF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSinusoidImageSourceIF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkSinusoidImageSourceIF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkSinusoidImageSourceIF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkSinusoidImageSourceIF2.Clone = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_Clone, None, itkSinusoidImageSourceIF2)
itkSinusoidImageSourceIF2.SetPhaseOffset = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_SetPhaseOffset, None, itkSinusoidImageSourceIF2)
itkSinusoidImageSourceIF2.GetPhaseOffset = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_GetPhaseOffset, None, itkSinusoidImageSourceIF2)
itkSinusoidImageSourceIF2.SetFrequency = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_SetFrequency, None, itkSinusoidImageSourceIF2)
itkSinusoidImageSourceIF2.GetFrequency = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_GetFrequency, None, itkSinusoidImageSourceIF2)
itkSinusoidImageSourceIF2_swigregister = _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_swigregister
itkSinusoidImageSourceIF2_swigregister(itkSinusoidImageSourceIF2)

def itkSinusoidImageSourceIF2___New_orig__():
    """itkSinusoidImageSourceIF2___New_orig__() -> itkSinusoidImageSourceIF2_Pointer"""
    return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2___New_orig__()

def itkSinusoidImageSourceIF2_cast(obj):
    """itkSinusoidImageSourceIF2_cast(itkLightObject obj) -> itkSinusoidImageSourceIF2"""
    return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF2_cast(obj)

class itkSinusoidImageSourceIF3(itkParametricImageSourcePython.itkParametricImageSourceIF3):
    """Proxy of C++ itkSinusoidImageSourceIF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkSinusoidImageSourceIF3_Pointer"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkSinusoidImageSourceIF3 self) -> itkSinusoidImageSourceIF3_Pointer"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_Clone(self)


    def SetPhaseOffset(self, _arg):
        """SetPhaseOffset(itkSinusoidImageSourceIF3 self, double const _arg)"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_SetPhaseOffset(self, _arg)


    def GetPhaseOffset(self):
        """GetPhaseOffset(itkSinusoidImageSourceIF3 self) -> double"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_GetPhaseOffset(self)


    def SetFrequency(self, _arg):
        """SetFrequency(itkSinusoidImageSourceIF3 self, itkFixedArrayD3 _arg)"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_SetFrequency(self, _arg)


    def GetFrequency(self):
        """GetFrequency(itkSinusoidImageSourceIF3 self) -> itkFixedArrayD3"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_GetFrequency(self)

    __swig_destroy__ = _itkSinusoidImageSourcePython.delete_itkSinusoidImageSourceIF3

    def cast(obj):
        """cast(itkLightObject obj) -> itkSinusoidImageSourceIF3"""
        return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkSinusoidImageSourceIF3

        Create a new object of the class itkSinusoidImageSourceIF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSinusoidImageSourceIF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkSinusoidImageSourceIF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkSinusoidImageSourceIF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkSinusoidImageSourceIF3.Clone = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_Clone, None, itkSinusoidImageSourceIF3)
itkSinusoidImageSourceIF3.SetPhaseOffset = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_SetPhaseOffset, None, itkSinusoidImageSourceIF3)
itkSinusoidImageSourceIF3.GetPhaseOffset = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_GetPhaseOffset, None, itkSinusoidImageSourceIF3)
itkSinusoidImageSourceIF3.SetFrequency = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_SetFrequency, None, itkSinusoidImageSourceIF3)
itkSinusoidImageSourceIF3.GetFrequency = new_instancemethod(_itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_GetFrequency, None, itkSinusoidImageSourceIF3)
itkSinusoidImageSourceIF3_swigregister = _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_swigregister
itkSinusoidImageSourceIF3_swigregister(itkSinusoidImageSourceIF3)

def itkSinusoidImageSourceIF3___New_orig__():
    """itkSinusoidImageSourceIF3___New_orig__() -> itkSinusoidImageSourceIF3_Pointer"""
    return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3___New_orig__()

def itkSinusoidImageSourceIF3_cast(obj):
    """itkSinusoidImageSourceIF3_cast(itkLightObject obj) -> itkSinusoidImageSourceIF3"""
    return _itkSinusoidImageSourcePython.itkSinusoidImageSourceIF3_cast(obj)


def sinusoid_image_source(*args, **kwargs):
    """Procedural interface for SinusoidImageSource"""
    import itk
    instance = itk.SinusoidImageSource.New(*args, **kwargs)
    return instance.__internal_call__()

def sinusoid_image_source_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.SinusoidImageSource, itkTemplate.itkTemplate):
        sinusoid_image_source.__doc__ = itk.SinusoidImageSource.values()[0].__doc__
    else:
        sinusoid_image_source.__doc__ = itk.SinusoidImageSource.__doc__




