# Generated by Django 2.2.4 on 2019-08-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='banquet_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ints_video',
        ),
    ]
