#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='pyconafrica',
      version='1.0.2',
      description='This package that enables you fetch BMRS data as json instead of XML',
      author='Edison Abahurire',
      author_email='abahedison@gmail.com',
      url='https://github.com/SimiCode/pyconafrica-json-api',
      py_modules=['pyconafrica'],
     )
