- name: Install packages and run zuul-nodepool-integration/start.sh
  shell:
    cmd: |
      sudo pip3 install .
      ./tools/zuul-nodepool-integration/start.sh
    chdir: "{{ zuul.projects['opendev.org/zuul/nodepool'].src_dir }}"
