# Generated by Django 2.1.11 on 2019-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0005_auto_20190809_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardspluginmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('uk-card-default', 'default'), ('uk-card-primary', 'primary'), ('uk-card-secondary', 'secondary')], max_length=20, null=True),
        ),
    ]
