[tool.poetry]
name = "wrarc"
version = "0.1.1"
description = "This is a wrapper around phabricator to make the interactions with tasks seamless and fast."
authors = ["Wasiur Rahman <wrahman@uber.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
wrarc = 'wrarc:main'
