dist: xenial

language: python

addons:
  apt:
    packages:
    - graphviz
    - libopenblas-dev

os:
  - linux

python:
  - "3.6"
  - "3.7"


install:
  # default python provides an incompatible version of numpy (1.15.x) for python 3.7
  - pip install --upgrade pip setuptools numpy scipy
  - pip install -e ".[test]"

script:
  - pytest
