
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-01T22:24:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "597e00d02629dcdfa9cfbb1c7cad63c05d3eff79",
 "version": "0.10.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
