# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: example/helloworld.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import example.helloworld_pb2


class GreeterBase(abc.ABC):

    @abc.abstractmethod
    async def SayHello(self, stream):
        pass

    def __mapping__(self):
        return {
            '/example.helloworld.Greeter/SayHello': grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                example.helloworld_pb2.HelloRequest,
                example.helloworld_pb2.HelloReply,
            ),
        }


class GreeterStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            '/example.helloworld.Greeter/SayHello',
            example.helloworld_pb2.HelloRequest,
            example.helloworld_pb2.HelloReply,
        )


class GreeterDBBase(abc.ABC):

    @abc.abstractmethod
    async def SayHello(self, stream):
        pass

    def __mapping__(self):
        return {
            '/example.helloworld.GreeterDB/SayHello': grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                example.helloworld_pb2.HelloRequest,
                example.helloworld_pb2.HelloReply,
            ),
        }


class GreeterDBStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            '/example.helloworld.GreeterDB/SayHello',
            example.helloworld_pb2.HelloRequest,
            example.helloworld_pb2.HelloReply,
        )
