#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['PyOffice']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['markdocs = markdocs:main']}

setup(name='PyOffice',
      version='0.2',
      description='Demonstrate docstrings and does nothing really.',
      author='vincent tang',
      author_email='vin.tang@gmail.com',
      url='https://github.com/mynameisvinn/pyoffice',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
