
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "36afd7b786f97a94f2c24901f04553f97d9d7693",
 "version": "2176"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
