# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_joboffer', '0002_auto_20190404_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='closingDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(to='djangoldp_skill.Skill'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
