# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_conversation', '0003_auto_20190503_0323'),
        ('djangoldp_joboffer', '0003_auto_20190524_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='conversation',
            field=models.ManyToManyField(blank=True, to='djangoldp_conversation.Conversation'),
        ),
    ]
