# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GeneralSection(Model):
    """GeneralSection.

    :param day_first:
    :type day_first: bool
    :param include_path:
    :type include_path: bool
    :param file_type:
    :type file_type: str
    :param comment_line_character:
    :type comment_line_character: str
    :param promote_headers_mode: Possible values include: 'None', 'Ungrouped',
     'FirstFile', 'Grouped', 'AllFiles', 'ConstantGrouped', 'SameAllFiles'
    :type promote_headers_mode: str or ~_restclient.models.enum
    :param skip_mode: Possible values include: 'None', 'Ungrouped',
     'FirstFile', 'Grouped', 'AllFiles'
    :type skip_mode: str or ~_restclient.models.enum
    :param handle_quoted_line_breaks:
    :type handle_quoted_line_breaks: bool
    :param source_properties_override:
    :type source_properties_override: ~_restclient.models.DataSourceProperties
    """

    _attribute_map = {
        'day_first': {'key': 'dayFirst', 'type': 'bool'},
        'include_path': {'key': 'includePath', 'type': 'bool'},
        'file_type': {'key': 'fileType', 'type': 'str'},
        'comment_line_character': {'key': 'commentLineCharacter', 'type': 'str'},
        'promote_headers_mode': {'key': 'promoteHeadersMode', 'type': 'str'},
        'skip_mode': {'key': 'skipMode', 'type': 'str'},
        'handle_quoted_line_breaks': {'key': 'handleQuotedLineBreaks', 'type': 'bool'},
        'source_properties_override': {'key': 'sourcePropertiesOverride', 'type': 'DataSourceProperties'},
    }

    def __init__(self, **kwargs):
        super(GeneralSection, self).__init__(**kwargs)
        self.day_first = kwargs.get('day_first', None)
        self.include_path = kwargs.get('include_path', None)
        self.file_type = kwargs.get('file_type', None)
        self.comment_line_character = kwargs.get('comment_line_character', None)
        self.promote_headers_mode = kwargs.get('promote_headers_mode', None)
        self.skip_mode = kwargs.get('skip_mode', None)
        self.handle_quoted_line_breaks = kwargs.get('handle_quoted_line_breaks', None)
        self.source_properties_override = kwargs.get('source_properties_override', None)
