[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "exceptor_magic"
author = "sam shleifer"
author-email = "sshleifer@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

