
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-08T16:35:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e11bf6263464cae2c0a6007b6fbc8b1054dd37d9",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
