[tool.poetry]
name = "dsu"
version = "1.4.0"
description = ""
authors = ["Nandhini Anand <cattykatrina4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
causality = "^0.0.9"
pymc = "^2.3"
optunity = "^1.1"
keras = "^2.2"
tensorflow = "^1.14"
gym = "^0.14.0"
scikit-learn = "^0.21.3"
scikit-MDR = "^0.4.4"
scikit-build = "^0.10.0"
scikit-gof = "^0.1.3"
scikit-data = "^0.1.3"
scikit-surprise = "^1.0"
umap = "^0.1.1"
seqlearn = "^0.2.0"
nltk = "^3.4"
gensim = "^3.8"
spacy = "^2.1"
xgboost = "^0.90.0"
hpsklearn = "^0.1.0"
tpot = "^0.10.2"
ortools = "^7.3"
cython = "^0.29.13"
lifelines = "^0.22.3"
tsfresh = "^0.12.0"
scikit-image = "^0.15.0"
scipy = "^1.3"
statsmodels = "^0.10.1"
robustats = "^0.1.2"
ace = "^0.3.2"
numpy = "^1.17"
patsy = "^0.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
