COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_PV_MATRIZ',
    'QTDE_TOTAL_RESUMOS_MATRIZ',
    'VL_TOTAL_CREDITOS_NORMAIS',
    'QTDE_CREDITOS_ANTECIPADOS',
    'VL_TOTAL_ANTECIPADO',
    'QTDE_AJUSTES_CREDITO',
    'VL_TOTAL_AJUSTES_CREDITO',
    'QTDE_AJUSTES_DEBITO',
    'VL_TOTAL_AJUSTES_DEBITO'
]