COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_PV',
    'BANCOS',
    'DT_CREDITO',
    'VL_TOTAL_CREDITO',
    'BRANCOS',
    'NRO_BANCO',
    'NRO_AGENCIA',
    'NRO_CONTA_CORRENTE',
    'DT_GERACAO_ARQUIVO',
    'DT_CREDITO_ANTECIPADO',
    'VL_TOTAL_ANTECIPADOS'
]