COLUMNS = [
    'TIPO_REGISTRO',
    'QTDE_MATRIZES_ARQUIVO',
    'QTDE_REGISTROS_ARQUIVO',
    'NRO_PV_GRUPO',
    'QTDE_TOTAL_RESUMOS_GRUPO',
    'VL_TOTAL_CREDITOS_NORMAIS',
    'QTDE_CREDITOS_ANTECIPADOS',
    'VL_TOTAL_ANTECIPADO',
    'QTDE_AJUSTES_CREDITO',
    'VL_TOTAL_AJUSTES_CREDITO',
    'QTDE_AJUSTES_DEBITO',
    'VL_TOTAL_AJUSTES_DEBITO'
]