
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "cd7e44401bd9310123e6a07dcdba7e65e881a7f2",
 "version": "0.24.5.b4758"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
