# Generated by Django 2.2.3 on 2019-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_seo', '0002_connectssmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterForSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя счечика', max_length=60, verbose_name='Имя')),
                ('counter', models.TextField(help_text='Код счечика или метрики', verbose_name='Код')),
                ('published', models.BooleanField(default=True, verbose_name='Включен')),
            ],
            options={
                'verbose_name': 'Счечики и аналитика для сайта',
                'verbose_name_plural': 'Счечики и аналитика для сайта',
            },
        ),
    ]
