# Generated by Django 2.2.3 on 2019-07-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms_seo', '0003_counterforsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterforsite',
            old_name='counter',
            new_name='code',
        ),
    ]
