[tool.poetry]
name = "find-missing"
version = "0.1.5"
description = ""
authors = ["MB <mb@m1k.pw>"]


[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
main = 'find_missing:from_list'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
