
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-09T20:53:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb571bf3cee2b8f2e47e0e32ff95efa504d0a04",
 "version": "1.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
