
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-01T14:47:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "974d9108d43b28f533969e147499f2dcdcfd3f9b",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
