
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T19:33:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "30015be17389690aeefa69b9768ea29bdd773dee",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
