# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0004_auto_20190117_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
    ]
