
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-02T16:33:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "071e028dbc0ad281bd34957dfedb97d3cf9ceab4",
 "version": "0.1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
