#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['pycryptodome>=3.8.2', 'six>=1.12.0']

setup(name='maltego_crypto_test',
      version='0.1.1',
      description='Maltego OAuth Crypto Helper',
      author='Tendai M',
      author_email='tm@maltego.com',
      url='http://tendai.co.zw',
      py_modules=['maltego_crypto_test'],
      install_requires=install_requires,
     )
