
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-31T15:06:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "be06e89f8ee5562846e01bb31c6f2f66e7458533",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
