# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_joboffer', '0004_joboffer_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobOffers', to=settings.AUTH_USER_MODEL),
        ),
    ]
