from pathlib import Path

LOG_PATH = str(Path("/") / "tmp" / "access.log")

REPORT_TICK = 10
REPORT_SECTIONS_TOP = 3

ALERT_TICK = 10
ALERT_TRAFFIC_THRESHOLD = 10
ALERT_TRAFFIC_UP = 2 * 60
ALERT_TRAFFIC_DOWN = 2 * 60

MONITOR_TICK = 0.5
MONITOR_LIMIT_MAX_LOG_LINES = None
MONITOR_LOG_LEVEL = "info"
