
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T14:53:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae78f1d204c6d8bdb53de0da0f83896768533503",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
