[tool.poetry]
name = "tinydb-dict"
version = "0.1.2"
description = "Simple dict-like class for TinyDB"
authors = ["Ali Ghahraei <aligf94@gmail.com>"]
license = "MIT"

repository = "https://github.com/AliGhahraei/tinydb-dict"
homepage = "https://github.com/AliGhahraei/tinydb-dict"
readme = 'README.md'
keywords = ['tinydb']

include = ['py.typed']

[tool.poetry.dependencies]
python = "^3.7"
tinydb = "^3.13"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
