# Version file autogenerated by the build process
version = '0.7.6rc2'
build = '434'
vcs_info = 'Git SHA1 cf0cd07d committed on 2019-08-15'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.7.6rc2"\nKSCONF_BUILD="434"\nKSCONF_VCS_INFO="Git SHA1 cf0cd07d committed on 2019-08-15"')
