language: python
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
script:
  - pyflakes redkyn
  - pylint redkyn
  - python setup.py nosetests
