
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-08-14T11:16:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cbf7abcca589ac7818aa1c68a9c9c3cd589fd0e",
 "version": "2019.8.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
