
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T15:41:35+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e13058a2e6d1ffeea7b8384b7b89cc3395b83fdb",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
