
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-08T12:07:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb05a7ea80afd3f08b28ba8a6e59768d03bd9bc3",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
