dist: xenial
sudo: false
language: python
python:
    - 3.5
    - 3.6
    - 3.7
install:
    - pip install -U pip
    - pip install -r requirements-optional.txt
script:
    - make all
after_success:
    - codecov
notifications:
    email:
        on_success: always
        on_failure: always
deploy:
  provider: pypi
  skip_existing: true
  # mshriver owned
  user: "@token"
  distributions: sdist bdist_wheel
  password: "pypi:AgEIcHlwaS5vcmcCJDA5OWM5YzdlLWZjMDItNDI5OS1iYjIyLTEzODVlNjZkZjk5YgACPHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJmYXV4ZmFjdG9yeSJdfSwgInZlcnNpb24iOiAxfQAABiB4bqeyKIWAgAYE09oFlAFQU9tlJiUDRIaXJEvQxXlmsg"
  on:
    tags: true
    repo: omaciel/fauxfactory

