[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "bloqly"
author = "Bloqly developers"
author-email = "team@bloqly.com"
home-page = "https://bloqly.com"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
    "requests >= 2.21.0",
    "pynacl >= 1.3.0",
]