
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-13T14:15:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a78a4f4296904c2ab768cc2a1b0d74c0e98b645",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
