
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T09:09:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3807a5abd139cbb5effb5f2a1ca7c2b3d30a3d8d",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
