# coding: utf-8

"""
    Key Manager API

    API Responsible for management the tools' keys   # noqa: E501

    OpenAPI spec version: v1
    Contact: paulossjunior@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Tool_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'tool': 'str',
        'secret': 'str',
        'organization_id': 'str'
    }

    attribute_map = {
        'url': 'url',
        'tool': 'tool',
        'secret': 'secret',
        'organization_id': 'organization_id'
    }

    def __init__(self, url=None, tool=None, secret=None, organization_id=None):  # noqa: E501
        """Tool_ - a model defined in Swagger"""  # noqa: E501

        self._url = None
        self._tool = None
        self._secret = None
        self._organization_id = None
        self.discriminator = None

        self.url = url
        self.tool = tool
        self.secret = secret
        self.organization_id = organization_id

    @property
    def url(self):
        """Gets the url of this Tool_.  # noqa: E501


        :return: The url of this Tool_.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Tool_.


        :param url: The url of this Tool_.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501
        if url is not None and len(url) > 200:
            raise ValueError("Invalid value for `url`, length must be less than or equal to `200`")  # noqa: E501
        if url is not None and len(url) < 1:
            raise ValueError("Invalid value for `url`, length must be greater than or equal to `1`")  # noqa: E501

        self._url = url

    @property
    def tool(self):
        """Gets the tool of this Tool_.  # noqa: E501


        :return: The tool of this Tool_.  # noqa: E501
        :rtype: str
        """
        return self._tool

    @tool.setter
    def tool(self, tool):
        """Sets the tool of this Tool_.


        :param tool: The tool of this Tool_.  # noqa: E501
        :type: str
        """
        if tool is None:
            raise ValueError("Invalid value for `tool`, must not be `None`")  # noqa: E501
        if tool is not None and len(tool) > 10:
            raise ValueError("Invalid value for `tool`, length must be less than or equal to `10`")  # noqa: E501
        if tool is not None and len(tool) < 1:
            raise ValueError("Invalid value for `tool`, length must be greater than or equal to `1`")  # noqa: E501

        self._tool = tool

    @property
    def secret(self):
        """Gets the secret of this Tool_.  # noqa: E501


        :return: The secret of this Tool_.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this Tool_.


        :param secret: The secret of this Tool_.  # noqa: E501
        :type: str
        """
        if secret is None:
            raise ValueError("Invalid value for `secret`, must not be `None`")  # noqa: E501
        if secret is not None and len(secret) > 200:
            raise ValueError("Invalid value for `secret`, length must be less than or equal to `200`")  # noqa: E501
        if secret is not None and len(secret) < 1:
            raise ValueError("Invalid value for `secret`, length must be greater than or equal to `1`")  # noqa: E501

        self._secret = secret

    @property
    def organization_id(self):
        """Gets the organization_id of this Tool_.  # noqa: E501


        :return: The organization_id of this Tool_.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this Tool_.


        :param organization_id: The organization_id of this Tool_.  # noqa: E501
        :type: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501
        if organization_id is not None and len(organization_id) > 10:
            raise ValueError("Invalid value for `organization_id`, length must be less than or equal to `10`")  # noqa: E501
        if organization_id is not None and len(organization_id) < 1:
            raise ValueError("Invalid value for `organization_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._organization_id = organization_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Tool_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tool_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
