language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
        - os: linux
          python: 3.6
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
        - os: linux
          python: 2.7
        - os: osx
          language: generic
          env: TOXENV=py27
    allow_failures:
        - os: osx
          language: generic
          env: TOXENV=py27
install:
  - pip install -r requirements.txt
  - python setup.py install
  - python -m pycm test
  - python -m pycm
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt --user ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade --upgrade-strategy=only-if-needed -r dev-requirements.txt ; fi
  - chmod +x Otherfiles/test.sh
script:
  - Otherfiles/test.sh
after_success:
  - codecov
