# Generated by Django 2.2.4 on 2019-08-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epic_admin.Organization', verbose_name='Organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
