# Generated by Django 2.2.4 on 2019-08-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_admin', '0002_auto_20190806_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
