# Generated by Django 2.2.4 on 2019-08-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_admin', '0004_organization_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax'),
        ),
    ]
