
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-05T12:36:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea0afa62c3487a936b5a1732c0a9cbcea1bdcdef",
 "version": "0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
