
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T00:19:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "af89ea87d18cb083ab19cbfda133f455313a9bcc",
 "version": "2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
