[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "chartsh"
author = "Joe Mountford"
author-email = "jbm112358@gmail.com"
home-page = "http://chartsh.com/ingest/docs/"

