
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-08T14:44:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f96f473cf172954c8d9f659910453209455e2e5d",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
