
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-06T16:26:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f600c15d50b6c0dbbd01f98e33e46122d844f18",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
