# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_profile', '0002_auto_20181218_1208'),
        ('djangoldp_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jabberID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jabberRoom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
