
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-05T13:04:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "474aea709e1bbd574e71b7d4dfef08c8673be26b",
 "version": "0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
