language: python
matrix:
    include:
        - python: 2.7
          sudo: true
          env: TOXENV=py27
        - python: 3.4
          sudo: true
          env: TOXENV=py34
        - python: 3.5
          sudo: true
          env: TOXENV=py35
        - python: 3.6
          sudo: true
          env: TOXENV=py36
        - python: 3.7
          dist: xenial
          sudo: true
          env: TOXENV=py37

install:
    - travis_retry pip install tox

script:
    - tox
