
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-31T18:15:27+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb87b5635d4529eec4063faa97b06597ccc2d8ff",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
