[tool.poetry]
name = "blaster_logger"
version = "0.1.0"
description = ""
authors = ["MB <mb@blaster.ai>"]
readme="README.md"
homepage="https://github.com/Blasterai/blaster-logger"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
