
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-12T17:10:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "75a30bc5744e636b1d28a89373835a7224d378c2",
 "version": "1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
