
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-17T06:24:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "66490b7441dd728a1cae4cdae38fb20e093913b7",
 "version": "v0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
