# Generated by Django 2.2.2 on 2019-08-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0036_auto_20190807_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeinitial',
            name='sae_reason',
            field=models.ForeignKey(help_text='If subject deceased, submit a Death Report', on_delete=django.db.models.deletion.PROTECT, to='edc_adverse_event.SaeReason', verbose_name='If "Yes", reason for SAE:'),
        ),
    ]
