[tool.poetry]
name = "find-missing"
version = "1.1.9"
description = ""
authors = ["MB <mb@m1k.pw>"]
license="MIT"
readme="README.md"
homepage="https://github.com/licht1stein/find-missing"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
find-missing = 'find_missing:main'
Find-Missing = 'find_missing:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
