dist: xenial
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.1
  - DJANGO=2.2

install:
  - pip install -q Django==$DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test axes --settings=axes.test_settings

matrix:
  allow_failures:
    - python: 2.7
      env: DJANGO=1.11
    - python: 2.7
      env: DJANGO=2.1
    - python: 2.7
      env: DJANGO=2.2
    - python: 3.5
      env: DJANGO=1.11
    - python: 3.5
      env: DJANGO=2.1
    - python: 3.5
      env: DJANGO=2.2
    - python: 3.6
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=2.1
    - python: 3.6
      env: DJANGO=2.2
    - python: 3.7
      env: DJANGO=1.8
    - python: 3.7
      env: DJANGO=1.11
    - python: 3.7
      env: DJANGO=2.1
    - python: 3.7
      env: DJANGO=2.2
  fast_finish: true

deploy:
  provider: pypi
  user: jazzband
  password:
    secure: TCH5tGIggL2wsWce2svMwpEpPiwVOYqq1R3uSBTexszleP0OafNq/wZk2KZEReR5w1Aq68qp5F5Eeh2ZjJTq4f9M4LtTvqQzrmyNP55DYk/uB1rBJm9b4gBgMtAknxdI2g7unkhQEDo4suuPCVofM7rrDughySNpmvlUQYDttHQ=
  server: https://jazzband.co/projects/django-axes/upload
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: jazzband/django-axes
    python: 3.6
