
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-31T16:30:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d68cb867665fd6ec8a6b7eab1707744011a1323",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
