COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_CARTAO',
    'DT_TRANSACAO',
    'NRO_RV_ORIGINAL',
    'NRO_PV_ORIGINAL',
    'DT_RV_ORIGINAL',
    'VL_TRANSACAO',
    'NRO_NSU',
    'NRO_AUTORIZACAO',
    'TID',
    'NRO_PEDIDO'
]