COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIACAO_PONTO_VENDA',
    'NRO_RESUMO_VENDAS',
    'DT_CV',
    'NRO_CV',
    'VL_BRUTO_CV',
    'MOTIVO_CANCELAMENTO',
    'DT_CREDITO',
    'NOVO_VL_CREDITO',
    'TIPO_TRANSACAO'
]