COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIACAO_PONTO_VENDA',
    'DT_LIQUIDACAO',
    'VL_LIQUIDADO',
    'NRO_NSU_TRANSACAO',
    'DT_TRANSACAO',
    'DT_VENCIMENTO',
    'VL_DESCONTO',
    'VL_BRUTO',
    'BANDEIRA'
]