# Generated by Django 2.2.3 on 2019-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='soc_icon/', verbose_name='Иконка'),
        ),
    ]
