
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T01:35:47-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ed15070e14caffbc88be4eb6c1c772e7f4aa63e",
 "version": "v0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
