# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: istsosproto/dataraster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='istsosproto/dataraster.proto',
  package='istsosproto.dataraster',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cistsosproto/dataraster.proto\x12\x16istsosproto.dataraster\"\x14\n\x06Raster\x12\n\n\x02id\x18\x01 \x01(\t2U\n\nDataRaster\x12G\n\x03get\x12\x1e.istsosproto.dataraster.Raster\x1a\x1e.istsosproto.dataraster.Raster\"\x00\x62\x06proto3')
)




_RASTER = _descriptor.Descriptor(
  name='Raster',
  full_name='istsosproto.dataraster.Raster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='istsosproto.dataraster.Raster.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Raster'] = _RASTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Raster = _reflection.GeneratedProtocolMessageType('Raster', (_message.Message,), {
  'DESCRIPTOR' : _RASTER,
  '__module__' : 'istsosproto.dataraster_pb2'
  # @@protoc_insertion_point(class_scope:istsosproto.dataraster.Raster)
  })
_sym_db.RegisterMessage(Raster)



_DATARASTER = _descriptor.ServiceDescriptor(
  name='DataRaster',
  full_name='istsosproto.dataraster.DataRaster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='istsosproto.dataraster.DataRaster.get',
    index=0,
    containing_service=None,
    input_type=_RASTER,
    output_type=_RASTER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATARASTER)

DESCRIPTOR.services_by_name['DataRaster'] = _DATARASTER

# @@protoc_insertion_point(module_scope)
