[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "maltego_crypto_test"
author = "Maltego Staff"
author-email = "support@maltego.com"
requires =["pycryptodome>=3.8.2","six>=1.12.0",]
home-page = "https://www.maltego.com"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "desc.md"
[tool.flit.metadata.requires-extra]
test = [
    "pytest >=5.0.1",
]