version: '3.7'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:10.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=todolist

volumes:
  postgres_data:

