# Generated by Django 2.1.11 on 2019-08-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_cardspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UkAccordionItemModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_ukaccordionitemmodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('open', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UkAccordionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_ukaccordionmodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('collapsible', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=True)),
                ('animation', models.BooleanField(default=True)),
                ('active', models.IntegerField(default=None)),
                ('duration', models.IntegerField(default=200)),
                ('transition', models.CharField(choices=[('linear', 'linear'), ('ease', 'ease'), ('ease-in', 'ease-in'), ('ease-in-out', 'ease-in-out'), ('ease-out', 'ease-out')], default='ease', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UkContainerModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_ukcontainermodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('container_expand', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UkGridModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_ukgridmodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('grid_gutter', models.CharField(choices=[('uk-grid-small', 'Small'), ('uk-grid-medium', 'medium'), ('uk-grid-large', 'large'), ('uk-grid-collapse', 'collapse')], max_length=20)),
                ('grid_divider', models.BooleanField(default=False)),
                ('grid_match', models.BooleanField(default=False, verbose_name='Match Height')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UkSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_uikit_uksectionmodel', serialize=False, to='cms.CMSPlugin')),
                ('extra_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('style', models.CharField(choices=[('uk-section-default', 'Default'), ('uk-section-muted', 'Muted'), ('uk-section-primary', 'Primary'), ('uk-section-secondary', 'Secondary')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
