# Generated by Django 2.1.11 on 2019-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0002_auto_20190809_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='uksectionmodel',
            name='style2',
            field=models.CharField(choices=[('uk-section-default', 'Default'), ('uk-section-muted', 'Muted'), ('uk-section-primary', 'Primary'), ('uk-section-secondary', 'Secondary')], default=None, max_length=200),
        ),
    ]
