# Generated by Django 2.1.11 on 2019-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0008_cardspluginmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_expand_xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_l',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_m',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_s',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_xl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
