[tool.poetry]
name = "apap"
version = "0.0.0-b3"
description = "Declarative and handy RESTful client factory"
authors = ["mtwtkman <yo@mtwtkman.dev>"]
license = "WTFPL"
readme = "README.rst"
classifiers = [
  "Topic :: Utilities",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7"
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "2.22.0"
mypy_extensions ="0.4.1"


[tool.poetry.dev-dependencies]
black = "19.3b0"
mypy = "0.720"
restructuredtext_lint = "^1"
pygments = "2.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
