# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.TextField(),
        ),
    ]
