# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_conversation', '0002_auto_20190227_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Conversation',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-dateCreated'], 'permissions': (('view_conversation', 'Read'), ('control_conversation', 'Control'))},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='thread',
            new_name='conversation',
        ),
    ]
