# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_conversation', '0003_auto_20190503_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-dateCreated']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['dateCreated']},
        ),
    ]
