
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-07T01:08:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "06e9fbf639aacbe83e4bb635d891208a0a4aa74f",
 "version": "v0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
