# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2019-08-06 12:18:05.386849
__version__ = '2.5.7'