# -*- coding: utf-8 -*-
from distutils.core import setup

packages = \
['asc']

package_data = \
{'': ['*'],
 'asc': ['data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_1.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_daniilS_2.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/aicommands_old.txt',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/asc.png',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/bscommands.txt',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/canvas.pks',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/commands.txt',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/icon.svg',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/pktext.tbl',
         'data/stdlib/*']}

install_requires = \
['PyQt5>=5,<6', 'QScintilla>=2,<3']

entry_points = \
{'console_scripts': ['asc-cli = asc.asc:main', 'asc-qt = asc.asc_qt:main']}

setup_kwargs = {
    'name': 'red-alien',
    'version': '2.0.1',
    'description': 'A compiler/decompiler for the script system found in GBA pokemon games',
    'long_description': "# The Red Alien Pokémon Script Compiler\n\nThis is the source repository for [Red Alien], a\ncompiler for the scripting system found in GBA Pokémon games.\n\nSee the [documentation] and [examples] for an overview of its\nfeatures.\n\n[Red Alien]: http://www.cosarara.me/redalien/\n[documentation]: http://www.cosarara.me/redalien/#docs\n[examples]: examples/\n\n## Running\n\nRed Alien is built using cross-platform technologies, so it should run\neverywhere. I build [windows binaries] every now and then.\nArch users can install its [AUR] package.\nThere is a *very* old build for Mac OSX which I don't recommend using;\nrun it from source instead. Same on other linux distributions or\noperating systems.\n\n[windows binaries]: http://www.cosarara.me/redalien/#windows\n[AUR]: https://aur.archlinux.org/packages/red-alien-git/\n\nRed alien is written in python and can be run directly from the\nsource files if you have all the dependencies installed:\n\nDependency | Arch package   | Debian/Ubuntu package\n---------- | -------------- | ---------------------\nPython 3   | `python`       | `python3`\nPyQt 5     | `python-pyqt5` | `python3-pyqt5`<br>(depends on `python3`)\nPython bindings for Qscintilla | `python-qscintilla-qt5` | `python3-pyqt5.qsci`<br>(depends on `python3-pyqt5`)\n\nIt can be installed system-wide (although it's not needed):\n\n    # ./setup.py install\n\nYou can run asc-cli for CLI or asc-qt for the GUI.\n\nIf you want pks syntax highlighting in vim, you can copy utils/pks.vim to\n$HOME/.vim/syntax/, and add the following line to your .vimrc:\nautocmd BufRead,BufNewFile *.pks set filetype=pks\n\n## Acknowledgements\n\nMost of the command's information was taken from PKSV's pokedef.h (Thanks!)\n\nThe headers in stdlib/ are taken from XSE.\n\n",
    'author': 'Jaume Delclòs Coll',
    'author_email': 'me@cosarara.me',
    'url': 'https://www.cosarara.me/redalien/',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3,<4',
}


setup(**setup_kwargs)
