COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_PV_CREDENCIADO',
    'NRO_RESUMO_CREDITO',
    'NRO_DOCUMENTO',
    'DT_EMISSAO',
    'DT_CREDITO',
    'VL_CREDITO',
    'CREDITO',
    'BANCO',
    'AGENCIA',
    'CONTA_CORRENTE',
    'COD_MOTIVO_CREDITO',
    'DESC_MOTIVO_CREDITO',
    'BANDEIRA'
]