COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_PV',
    'NRO_DOCUMENTO',
    'DT_LANCAMENTO',
    'VL_LANCAMENTO',
    'CREDITO',
    'BANCO',
    'AGENCIA',
    'CONTA_CORRENTE',
    'NRO_RV_CORRESPONDENTE',
    'DT_RV_CORRESPONDENTE',
    'VL_CREDITO_ORIGINAL',
    'DT_VENCIMENTO_ORIGINAL',
    'NRO_PARCELA_TOTAL',
    'VL_BRUTO',
    'VL_TAXA_DESCONTO',
    'NRO_PV_ORIGINAL',
    'BANDEIRA'
]

