COLUMNS = [
    'TIPO_REGISTRO',
    'DATA_EMISSAO',
    'REDE',
    'EXTRATO_MOVIMENTACAO_FINANCEIRA',
    'NOME_COMERCIAL',
    'SEQUENCIA_MOVIMENTO',
    'NRO_PV_GRUPO_MATRIZ',
    'TIPO_PROCESSAMENTO',
    'VERSAO_ARQUIVO'
]