COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_PV',
    'QTDE_CONSULTAS_REALIZADAS_PERIODO',
    'VL_TOTAL_CONSULTAS_PERIODO',
    'DT_INICIO_PERIODO_CONSULTA',
    'DT_FIM_PERIODO_CONSULTA',
    'VL_CONSULTA_PERIODO',
    'BANDEIRA'
]