language: python
dist: xenial
os: linux
python:
  - "3.7"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y tshark xdg-utils

install:
    - pip install setuptools
    - pip install -e .[develop]

after_success:
    - python setup.py sdist --formats zip,gztar

# command to run tests
script: python setup.py test
