
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T17:19:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "616a2324bc973f4939ded5d883acf4066c8ae821",
 "version": "2020.0.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
