# Generated by Django 2.2.3 on 2019-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190717_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
