[tool.poetry] 
name = "udp-filetransfer"
version = "0.4.5"
description = "Reliable filetransfer over UDP"
authors = ["golyalpha <golyalpha@gmail.com>"]
license = "MPL-2.0"
readme = "readme.md"
repository = "https://gitlab.com/Trickster-Animations/udp-filetransfer"
homepage = "https://gitlab.com/Trickster-Animations/udp-filetransfer"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Natural Language :: English",
  "Topic :: Communications :: File Sharing",
  "Topic :: Internet",
  "Topic :: System :: Archiving :: Backup",
  "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
pylint = "^2.3"
rope = "^0.12.0"
nuitka = "^0.6.2"
semver = "^2.8"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
