[tool.poetry]
name = "gns3fy"
version = "0.1.0"
description = "Python wrapper around GNS3 Server API"
authors = ["David Flores <davidflores7_8@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
pydantic = "^0.31.0"

[tool.poetry.dev-dependencies]
ipython = "^7.7"
pytest = "^5.0"
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
