
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-02T15:47:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb82fa0aa54e3f78f65cb27f2f222c852ec22535",
 "version": "1.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
