[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

######################
# FLIT CONFIGURATION #
######################

[tool.flit.metadata]
# General Meta data
dist-name = "RED-Metrics-Tracker"
module = "red"
author = "Nils Diefenbach"
author-email = "nlsdfnbch.foos@kolabnow.com"
home-page = "https://github.com/nlsdfnbch/RED-Metrics-Tracker"
description-file = "README.rst"

# Pypi Requirements
requires-python = ">3.6"
requires = [
    'prometheus_client',
    'flask',
]

# Classifiers, Licensing, keywords for pypi.
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
]
keywords = "red-metrics, prometheus, instrumentation, metrics"

[tool.flit.metadata.requires-extra]
# Extended dependencies required for development and testing. Flit installs
# these automatically.
test = ["pytest"]
dev = [
    "black==19.3b0",
    "flake8-bugbear==18.8.0",
    "flake8-tuple==0.2.13",
    "flake8==3.7.5",
    "isort==4.3.16",
    "pytest==4.5.0",
]

[tool.flit.metadata.urls]
# All sorts of URLs to display on the pypi page.
GitHub = "https://github.com/nlsdfnbch/RED-Metrics-Tracker"
"Bug Tracker" = "https://github.com/nlsdfnbch/RED-Metrics-Tracker/issues"


#######################
# ISORT CONFIGURATION #
#######################

[tool.isort]
line_length = 99
known_future_library = "future"
known_first_party = "scenario_player, raiden"
default_section = "THIRDPARTY"
combine_as_imports = true
# black compatibility
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true


#######################
# BLACK CONFIGURATION #
#######################

[tool.black]
line-length = 99
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | test
  | docs
)/
'''
