#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['red']

package_data = \
{'': ['*']}

install_requires = \
['prometheus_client', 'flask']

extras_require = \
{'dev': ['black==19.3b0',
         'flake8-bugbear==18.8.0',
         'flake8-tuple==0.2.13',
         'flake8==3.7.5',
         'isort==4.3.16',
         'pytest==4.5.0'],
 'test': ['pytest']}

setup(name='RED-Metrics-Tracker',
      version='0.1.1',
      description='RED Metrics tracker able to instrument flask views using prometheus metrics.',
      author='Nils Diefenbach',
      author_email='nlsdfnbch.foos@kolabnow.com',
      url='https://github.com/nlsdfnbch/RED-Metrics-Tracker',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>3.6',
     )
