# Generated by Django 2.2.3 on 2019-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_seo', '0004_auto_20190717_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterforsite',
            options={'verbose_name': 'Счетчики и аналитика для сайта', 'verbose_name_plural': 'Счетчики и аналитика для сайта'},
        ),
        migrations.AlterField(
            model_name='counterforsite',
            name='code',
            field=models.TextField(help_text='Код счетчика или метрики', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='counterforsite',
            name='name',
            field=models.CharField(help_text='Имя счетчика', max_length=60, verbose_name='Имя'),
        ),
    ]
