
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-08T15:34:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd09c87f329fdcf94ccdf0e7fc7c34455eb709fb",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
