# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
