[tool.poetry]
name = "find-missing"
version = "0.1.16"
description = ""
authors = ["MB <mb@m1k.pw>"]
packages = [{include = "find_missing"}]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
