# Generated by Django 2.2.4 on 2019-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='is_default',
            field=models.BooleanField(default=False, unique=True, verbose_name='Язык по умолчанию'),
        ),
    ]
