
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-07T16:21:16+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0379219b0d3d150f57f296f61d7c08dea9a5ef9c",
 "version": "0.9.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
