# Define the services that make up your app in docker-compose.yml so they can be run together in an isolated environment.
# Docker Compose is an official tool that helps you manage your Docker containers 
# by letting you define everything through a docker-compose.yml file.

version: '3.1' # Specify version of Docker Compose

services:
  web:
    build: .
    # build the current directory, execute runserver on startup
    command: python /code/manage.py migrate
    command: python /code/manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      # expose port 8000 which is Django’s default so the container will expose it, too.
      - 8000:8000

# Run docker-compose up and Compose starts and runs your entire app.
# Notes on commands
# The following only builds the images, does not start the containers:
# docker-compose build

# The following builds the images if the images do not exist and starts the containers:
#   docker-compose up

# If you add the --build option, it is forced to build the images even when not needed:
#   docker-compose up --build

# The following skips the image build process:
#   docker-compose up --no-build

# If the images aren't built beforehand, it fails.
