
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T04:17:48-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "23f9ac8933803f58e1264ad55275db5ff5fb1b9e",
 "version": "v0.5.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
