__version__ = "0.2.12"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.iscsiapi.git'
__git_head_hash__ = '4612c3dba3a54c17ec66dfff9c95a9c6b9b79adf'
__git_head_subject__ = u'Finished Release v0.2.12'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2019-08-05 18:05:24'
