# Generated by Django 2.2.3 on 2019-07-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desk_cont',
            new_name='description',
        ),
    ]
