
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-29T17:28:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "716dca521e1fdf191fd444e6e2f127047e3b0e3c",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
