
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T01:27:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2781f712a26f60ccd0585e32d95ebf991836b224",
 "version": "5.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
