
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-13T11:13:55+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1462dec7b046dd650e4b7f19d9c7aa66de54cf90",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
