[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "maltego_crypto_test"
author = "Tendai M"
author-email = "tm@maltego.com"
requires =["pycryptodome>=3.8.2","six>=1.12.0",]
home-page = "http://tendai.co.zw"
classifiers = ["License :: OSI Approved :: MIT License"]

