
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-02T16:35:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e475d4185c95dd1dd7eb0337accdc1d2a74c4158",
 "version": "0.1.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
