# This file was auto-generated by ZETUP
#
# Zimmermann's Extensible Tools for Unified Project setups
#
# https://github.com/zimmermanncode/zetup


from __future__ import absolute_import

import sys
import os
from collections import OrderedDict

from zetup.version import Version
from zetup.dist import Distribution
from zetup.requires import Requirements
from zetup.extras import Extras
from zetup.package import Packages, Package
from zetup.notebook import Notebook



zfg = sys.modules[__name__]

NAME = 'zcons'

URL = 'https://github.com/zimmermanncode/zcons'

LICENSE = 'LGPLv3'

EXTRAS = Extras([

], zfg=zfg)

KEYWORDS = ['zetup', 'setup', 'scons', 'sconstruct', 'sconscript', 'install', 'installer', 'installation', 'build', 'builder', 'construct', 'construction', 'compile', 'compiler', 'compilation', 'zimmermann', 'zimmermanncode', 'userzimmermann', 'python3', 'python3']

CLASSIFIERS = ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)', 'Operating System :: OS Independent', 'Topic :: Software Development', 'Topic :: Utilities', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7']

SETUP_REQUIRES = Requirements("""

zetup[commands]
""", zfg=zfg)

PYTHON = ['2.7', '3.5', '3.6', '3.7']

KEEP_MADE = ['setup.py']

REQUIRES = Requirements("""
#py2 path.py ~= 11.5.0 #import path
#py3 path.py >= 11.5.0 #import path
zetup >= 0.2.58

""", zfg=zfg)

SETUP_KEYWORDS = None

TEST_COMMANDS = ['py.test -v test']

PACKAGES = Packages([

Package('zcons',
  sources=[
    'script.py',
    '__main__.py',
    '__init__.py',
    'error.py'
    ],
  subpackages=[
    
    ],
  )

  ], root=os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

SCRIPTS = {'zcons': 'zcons.script:run'}

NO_MAKE = ['tox.ini']

in_repo = True

MODULES = []

EMAIL = 'zimmermann.code@gmail.com'

VERSION = Version('0.1rc3.dev17')

DESCRIPTION = "Zimmermann's SCons wrapper"

TITLE = 'zcons'

SETUP_HOOKS = []

AUTHOR = 'Stefan Zimmermann'

FORCE_MAKE = True

DISTRIBUTION = Distribution(zfg)