# Generated by Django 2.2.3 on 2019-07-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'pages'), ('model', 'pages')), models.Q(('app_label', 'news'), ('model', 'post')), models.Q(('app_label', 'news'), ('model', 'category')), models.Q(('app_label', 'contact'), ('model', 'contact')), models.Q(('app_label', 'oms-gallery'), ('model', 'gallery')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Ссылка на'),
        ),
    ]
