
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-02T12:57:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2017aaf4593c5f6ed2d7ed49d0acc78612001a4b",
 "version": "1.36.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
