# Generated by Django 2.2.3 on 2019-07-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('abstractlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='languages.AbstractLang')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Тест')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('activate', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('template', models.CharField(default='pages/home.html', max_length=500, verbose_name='Шаблон')),
                ('slug', models.SlugField(blank=True, default='', help_text='Укажите url', max_length=500, null=True, unique=True, verbose_name='URL')),
            ],
            bases=('languages.abstractlang',),
        ),
    ]
