#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['datapungibea', 'datapungibea.config', 'datapungibea.tests']

package_data = \
{'': ['*']}

setup(name='datapungibea',
      version='0.8',
      description='Connects to BEA API and enriches data output; get vintage BEA data',
      author='James Otterson',
      author_email='jjotterson@gmail.com',
      url='https://github.com/jjotterson/datapungibea',
      packages=packages,
      package_data=package_data,
     )
