
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-06T20:36:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "969d89d428707003c1c9ba4842c3653adb9074ba",
 "version": "0.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
