
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-06T17:29:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3e412b42d2e4651dfcb79a608b69e515c9c5c47",
 "version": "v0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
