
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6a1ae9c21e92a353196577444b7f085c272ceff5",
 "version": "2174"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
