
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T06:55:16-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "889f9a40f72b3bb3ccbc71e9081f650b0e46e2be",
 "version": "v0.5.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
