# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='djangoldp_invoice.CustomerInvoice'),
        ),
        migrations.AlterField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='djangoldp_invoice.Batch'),
        ),
    ]
