# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0002_auto_20181206_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='htAmount',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='htAmount',
        ),
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='tvaRate',
            field=models.DecimalField(choices=[(0.0, 'exonération de TVA'), (20.0, '20%')], decimal_places=2, default=20.0, max_digits=4),
        ),
    ]
