# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0002_move_jabber'),
        ('djangoldp_invoice', '0003_auto_20190114_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoldp_project.Customer'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoldp_project.Project'),
        ),
    ]
