# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0005_auto_20190327_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='additionalText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
