# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0006_customerinvoice_additionaltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceinvoice',
            name='uploadUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
