
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T17:32:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae01786fe7f7e839fdd3ea1343c5321d14827180",
 "version": "2020.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
