# Generated by Django 2.2.3 on 2019-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190717_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Телефон'),
        ),
    ]
