[tool.poetry]
name = "FirstApp_ku34"
version = "0.1.1"
description = ""
authors = ["Asadur Rahman <asadur.rahman@oscillosoft.com.au>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
