
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-05T12:05:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ddc910932cf162c13f7ae28d247dfd5f7753286",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
