# Generated by Django 2.1.11 on 2019-08-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0003_uksectionmodel_style2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uksectionmodel',
            name='style2',
        ),
    ]
