# Generated by Django 2.1.11 on 2019-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0004_remove_uksectionmodel_style2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukgridmodel',
            name='flex',
            field=models.CharField(blank=True, choices=[('uk-flex-left', 'left'), ('uk-flex-center', 'center'), ('uk-flex-right', 'right'), ('uk-flex-between', 'between'), ('uk-flex-around', 'around')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='masonry',
            field=models.BooleanField(default=False),
        ),
    ]
