# Generated by Django 2.1.11 on 2019-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0007_cardspluginmodel_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardspluginmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('uk-card-small', 'small'), ('uk-card-large', 'large')], max_length=20, null=True),
        ),
    ]
