
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-06T08:19:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5edb0151f9baa531989d8fb08030aa20806ae67",
 "version": "v0.5.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
