
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T09:20:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7133473a00531e07d485eefa13b9ffb0c3c2a364",
 "version": "0.0.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
