# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '0.4'
__version_short__ = '0.4'
__version_long__ = '0.4-0-g16caf130'
__version_post__ = '0'
__version_commit__ = '16caf130'
__version_date__ = '2019-07-25 13:57:51 -0400'
__version_dirty__ = False
__build_date__ = '2019-08-13'
__build_time__ = '13:30:50.789422'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
