
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-05T18:25:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc3ffcdd8a2232dc6f1c1a77ef427bed75fcc10c",
 "version": "0.163"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
