
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-24T11:44:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "14d027f481ffbc9786cd6797e1fd7b91e7fe04a7",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
