
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-09T17:04:06+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4ba05da6916547f2d015911ea18984b582c75ba",
 "version": "2.0.0-beta.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
