# Generated by Django 2.2.1 on 2019-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_shoppinglist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
            preserve_default=False,
        ),
    ]
