# Generated by Django 2.2.1 on 2019-07-03 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_auto_20190703_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
            preserve_default=False,
        ),
    ]
