# Generated by Django 2.2.1 on 2019-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0006_auto_20190703_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
