# Generated by Django 2.2.1 on 2019-07-03 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0007_auto_20190703_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 10, 25, 29, 348395)),
        ),
    ]
