# Generated by Django 2.2.1 on 2019-07-05 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0014_auto_20190705_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 7, 43, 35, 422917, tzinfo=utc)),
        ),
    ]
