[tool.poetry]
name = "graphql-relay"
version = "3.0.0a1"
description = """
Relay library for graphql-core-next"""
licese="MIT"
authors = [
    "Syrus Akbary <me@syrusakbary.com>",
    "Christoph Zwerschke <cito@online.de>"
]
readme="README.md"
homepage="https://github.com/graphql-python/graphql-relay-py"
repository="https://github.com/graphql-python/graphql-relay-py"
documentation="https://github.com/graphql-python/graphql-relay-py"
keywords="graphql relay api"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7"
]
packages = [
    { include = "graphql_relay", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"
graphql-core = "^3.0.0a0"

[tool.poetry.dev-dependencies]
pytest = "^5"
pytest-asyncio = ">=0.10"
pytest-cov = "^2.7"
pytest-describe = ">=0.12"
pyyaml = "^5.1"
black = ">=19.3b0"
flake8 = "^3.7"
mypy = ">=0.720"
codecov = "^2"
check-manifest = ">=0.39"
bump2version = ">=0.5"
tox = "^3.13"

[tool.black]
target-version = ['py36', 'py37', 'py38']
[build-system]
requires = ["poetry>=0.12.16"]
build-backend = "poetry.masonry.api"
