suite/rv32i_m/I/I-ADD-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-ADDI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-AND-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-ANDI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-AUIPC-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BEQ-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BGE-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BGEU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BLT-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BLTU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-BNE-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRC-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRCI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRS-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRSI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRW-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-CSRRWI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-DELAY_SLOTS-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-EBREAK-01.S:
  commit_id: fa77193f0e68bc42949869266e994bb7b2d58d0b
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-ECALL-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-ENDIANESS-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-FENCE.I-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-IO.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-JAL-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-JALR-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LB-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LBU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LH-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LHU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LUI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-LW-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-MISALIGN_JMP-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-MISALIGN_LDST-02.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-NOP-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-OR-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-ORI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-RF_size-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-RF_width-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-RF_x0-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SB-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SH-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLL-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLLI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLT-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLTI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLTIU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SLTU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SRA-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SRAI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SRL-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SRLI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SUB-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-SW-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-XOR-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/I/I-XORI-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-DIV-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-DIVU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-MUL-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-MULH-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-MULHSU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-MULHU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-REM-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
suite/rv32i_m/M/M-REMU-01.S:
  commit_id: d50921ef64708678832770fd842355aa2b0684af
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
