[tool.poetry]
name = "liepa-tts"
version = "0.1.0"
description = "Python bindings for Lithuanian language synthesizer from LIEPA project"
authors = ["Ozymandias <tomas.rav@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/OzymandiasTheGreat/liepa-tts"
repository = "https://github.com/OzymandiasTheGreat/liepa-tts"
keywords = ["tts", "text2speech", "lithuanian"]
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"Programming Language :: C",
	"Programming Language :: C++",
	"Topic :: Multimedia :: Sound/Audio :: Sound Synthesis",
	"Topic :: Multimedia :: Sound/Audio :: Speech"
]

build = "build.py"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
