
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-12T21:43:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "96a201509051eddcfda3426fca7f85075f919848",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
