name: auth_users
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.29'
title: 'Custom users authentication'
icon: users
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/routing.es
    - resources/js/controllers/index.controller.es
    - resources/partial/index.html
    - ng:ajenti.auth.users
