
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T21:07:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed06cf47230a135d756e4f12f81cf4de5c5361c0",
 "version": "0.1.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
