
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-08-13T16:04:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b6fe477739e812af38811d103467f0e1beece74",
 "version": "2019.8.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
