__version__ = "0.1.20"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.logs_collector.git'
__git_head_hash__ = 'ae176501e20dc41ae97d34ddbecf8e9452654bc5'
__git_head_subject__ = u'Finished Release v0.1.20'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2019-08-05 18:04:28'
