
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-11T15:25:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "33d25af15cd72ab10992b30f27a7a8e8cfae00fd",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
