# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FeatureProfiles(Model):
    """FeatureProfiles.

    :param profile_date:
    :type profile_date: datetime
    :param results:
    :type results: list[~_restclient.models.ProfileResult]
    """

    _attribute_map = {
        'profile_date': {'key': 'profileDate', 'type': 'iso-8601'},
        'results': {'key': 'results', 'type': '[ProfileResult]'},
    }

    def __init__(self, profile_date=None, results=None):
        super(FeatureProfiles, self).__init__()
        self.profile_date = profile_date
        self.results = results
