# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v33</h1>       <p>Introduced in Cloudera Manager 6.3.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "cm-client"
VERSION = "33.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Cloudera Manager API",
    author_email="",
    url="",
    keywords=["Swagger", "Cloudera Manager API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="Cloudera Manager API client 33.0.0 for API version 33 introduced in Cloudera Manager 6.3.0"
)
