# Generated by Django 2.2.1 on 2019-07-03 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0008_auto_20190703_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 11, 30, 9, 831010, tzinfo=utc)),
        ),
    ]
