# Generated by Django 2.2.1 on 2019-07-03 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0010_auto_20190703_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 11, 49, 16, 841759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
