# Generated by Django 2.2.1 on 2019-07-04 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0011_auto_20190703_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 23, 18, 163640, tzinfo=utc)),
        ),
    ]
