# Generated by Django 2.2.1 on 2019-07-05 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0015_auto_20190705_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 7, 45, 22, 731484, tzinfo=utc)),
        ),
    ]
