# Generated by Django 2.2.1 on 2019-07-05 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0019_auto_20190705_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 46, 34, 279685, tzinfo=utc)),
        ),
    ]
