# Generated by Django 2.2.1 on 2019-07-05 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0020_auto_20190705_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 48, 55, 641787, tzinfo=utc)),
        ),
    ]
