
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-15T08:18:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "12a7692cfd99b9cbe8a4701de3bc1f6417b0a7e8",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
