
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-31T17:52:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a7754ebd05db5bc346d3cca0ebd866269acc08c",
 "version": "v1.1-beta.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
