# Generated by Django 2.1.2 on 2019-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190731_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(3, '论坛'), (1, '店铺'), (2, '文章')], default=1, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='标题'),
        ),
    ]
