# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_data(apps, schema_editor):
    Circle = apps.get_model('djangoldp_circle', 'Circle')
    for circle in Circle.objects.all():
        circle.jabberID = circle.chatConfig.jabberID
        circle.jabberRoom = circle.chatConfig.jabberRoom
        circle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0002_auto_20190110_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='jabberID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='jabberRoom',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migrate_data),
    ]
