# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0004_remove_circle_chatconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={},
        ),
    ]
