# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0005_auto_20190404_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
