
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-07T13:32:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f51d2e90532ec1dc991b67600f3458b28b4cf44e",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
