[tool.poetry]
name = "lcg-neuro-plx"
version = "0.2.1"
description = "Parsing of PLX neurophysiological data files in Python"
authors = ["Pedro Asad <pasad@lcg.ufrj.br>"]
repository = "https://gitlab.com/lcg/neuro/python-plx"
homepage = "https://lcg.gitlab.io/neuro/python-plx"
documentation = "https://lcg.gitlab.io/neuro/python-plx"
license = "MIT"
readme = "README.rst"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development",
    "Topic :: Software Development :: Version Control :: Git",
]
packages = [
    { include = "plx", from = "src" },
    { include = "recparse.py", from = "src" },
]
include = [
    "ext/**/*.cpp",
    "ext/**/*.h",
]
build = "build_extensions.py"

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.1"
click = {version = "^7.0",optional = true}
numpy = "^1.16"
pedroasad-attrs-patch = "^0.2.1"
pedroasad-marshmallow-patch = "^0.1.1"
pint = "^0.9.0"
wrapt = "^1.11"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
bumpversion = "^0.5.3"
codecov = "^2.0"
pre-commit = "^1.17"
pybind11 = "^2.3"
pytest = "^5.0"
pytest-cov = "^2.7"
recommonmark = "^0.5.0"
sphinx = "^2.1"
sphinx-click = "^2.2"
sphinx_rtd_theme = "^0.4.3"
sphinxcontrib-bibtex = "^0.4.2"
toml = "^0.10.0"

[tool.poetry.extras]
all = ["click"]
cli = ["click"]

[build-system]
build-backend = "poetry.masonry.api"
requires = [
    "poetry>=0.12",
    "pybind11>=2.3.0",
]
