
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-09T15:35:26-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "18fb789636fbe3f580edeb558a9cfb09fa786a66",
 "version": "v2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
