stages:
  - test
  - deploy

run_pytests:
  image: python:3.6
  stage: test
  before_script:
   - pip install .
   - pip install pytest
  script:
  - python -m pytest tests/
  only:
  - merge_requests

deploying_to_pypi:
  image: python:3.6
  stage: deploy
  before_script:
    - python setup.py sdist
    - pip install twine
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
