
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-15T11:38:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "55fee77ca3b0ea3b1abae5d19397b87f69267ce3",
 "version": "v0.8.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
