
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T11:50:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c09372a1f9fff80f4ca6cb49e82bedda4a1309e6",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
