
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-14T15:38:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c6d1f0c8aeddd9b4bfb00e3a1c0abb5040fa82b",
 "version": "v0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
