
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T10:33:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eec754350697cbd6322410597f98cd2d2c55b288",
 "version": "1.8.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
