[tool.poetry]
name = "pedroasad-marshmallow-patch"
version = "0.2.0"
description = "A set of patches to the excellect marshmallow library"
authors = ["Pedro Asad <pasad@lcg.ufrj.br>"]
repository = "https://gitlab.com/psa-exe//python-marshmallow-patch"
homepage = "https://psa-exe.gitlab.io/python-marshmallow-patch"
documentation = "https://psa-exe.gitlab.io/python-marshmallow-patch"
license = "MIT"
readme = "README.md"
packages = [
    { include = "marshmallow_patch", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"
marshmallow = "^2.19"
marshmallow_annotations = "^2.4"
numpy = { version = "^1.16", optional = true }
pint = { version = "^0.9.0", optional = true }

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
bumpversion = "^0.5.3"
codecov = "^2.0"
pre-commit = "^1.17"
pytest = "^5.0"
pytest-cov = "^2.7"
recommonmark = "^0.5.0"
sphinx = "^2.1"
sphinx_rtd_theme = "^0.4.3"
toml = "^0.10.0"

[tool.poetry.extras]
all = ["numpy", "pint"]
numpy = ["numpy"]
pint = ["pint"]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
