name: augeas
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.16'
title: 'Augeas API'
icon: cog
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/services/augeas.service.es
    - resources/js/services/aug.service.es
    - ng:ajenti.augeas
