# Generated by Django 2.1.11 on 2019-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ukgridmodel',
            old_name='grid_divider',
            new_name='divider',
        ),
        migrations.RenameField(
            model_name='ukgridmodel',
            old_name='grid_match',
            new_name='match',
        ),
        migrations.RemoveField(
            model_name='ukgridmodel',
            name='grid_gutter',
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_expand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_expand_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_expand_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='child_width_expand_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ukgridmodel',
            name='gutter',
            field=models.CharField(blank=True, choices=[('uk-grid-small', 'Small'), ('uk-grid-medium', 'medium'), ('uk-grid-large', 'large'), ('uk-grid-collapse', 'collapse')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uksectionmodel',
            name='style',
            field=models.CharField(choices=[('uk-section-default', 'Default'), ('uk-section-muted', 'Muted'), ('uk-section-primary', 'Primary'), ('uk-section-secondary', 'Secondary')], default=None, max_length=200),
        ),
    ]
