# Generated by Django 2.1.11 on 2019-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_uikit', '0006_cardspluginmodel_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardspluginmodel',
            name='hover',
            field=models.BooleanField(default=False),
        ),
    ]
