# Generated by Django 2.2.3 on 2019-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoblock',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='infoblock',
            name='section',
        ),
    ]
