# Generated by Django 2.2.3 on 2019-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя поисковой системы', max_length=60, verbose_name='Имя')),
                ('key', models.CharField(max_length=150, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Подключение ПС',
                'verbose_name_plural': 'Подключение ПС',
            },
        ),
    ]
