
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-02T14:37:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0dd0bf69855ddc48f233b2f265203fa6f5648cb",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
