// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `Instrumentation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ICE_API_EXPORTS
#   define ICE_API_EXPORTS
#endif
#include <Ice/Instrumentation.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 5
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

}

}

namespace Ice
{
}

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::Observer* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::ThreadObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::ConnectionObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::DispatchObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::ChildInvocationObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::RemoteObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::CollocatedObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::InvocationObserver* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::ObserverUpdater* p) { return p; }

ICE_API ::Ice::LocalObject* Ice::Instrumentation::upCast(::Ice::Instrumentation::CommunicatorObserver* p) { return p; }
