# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0006_auto_20190123_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='companyName',
            new_name='name',
        ),
    ]
