# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='token')),
                ('token_create_time', models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='token\u521b\u5efa\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5f53\u524d\u5fae\u4fe1token',
                'verbose_name_plural': '\u5f53\u524d\u5fae\u4fe1token',
            },
        ),
    ]
