# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0008_auto_20190304_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
    ]
