
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-07T15:28:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7365cbac61e0f581cebed7258ad495d884f04909",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
