
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-08T15:09:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5752972a14b5645efeaf7bc7f78798e3e862d5ba",
 "version": "v2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
