
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T16:13:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "87c7ddb00cf56a8a56d27e62ae793ff2f7624c93",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
