[tool.poetry]
name = "kbench"
version = "0.2.1"
description = "Benchmarking tool for Kubernetes clusters"
authors = ["Keichi Takahashi <keichi.t@me.com>"]
license = "MIT"
repository = "https://github.com/keichi/kbench/"
homepage = "https://github.com/keichi/kbench/"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Benchmark",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
kbench = "kbench.__main__:cli"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.3.2"
kubernetes = "^10.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
