# Generated by Django 2.2.3 on 2019-07-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='activate',
            new_name='published',
        ),
    ]
