# Generated by Django 2.2.3 on 2019-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190717_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Тест'),
        ),
    ]
