COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIACAO_MATRIZ_OU_GRUPO_COMERCIAL',
    'NRO_RESUMO_VENDAS',
    'DT_CV',
    'VL_RECARGA',
    'NRO_COMPROVANTES',
    'NRO_TELEFONE',
    'BANDEIRA',
    'COD_AUORIZACAO'
]