COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIACAO_PONTO_VENDA',
    'DATA_CREDITO',
    'DATA_RESUMO_VENDAS',
    'NRO_RESUMO_VENDAS',
    'QTDE_COMPROVANTES_VENDAS',
    'VL_BRUTO',
    'VL_DESCONTO',
    'VL_LIQUIDO',
    'TIPO_DE_RESUMO',
    'BANCO',
    'AGENCIA',
    'CONTA_CORRENTE',
    'BANDEIRA'
]