COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIACAO_MATRIZ_OU_GRUPO_COMERCIAL',
    'QTDE_RESUMOS_VENDAS',
    'QTDE_COMPROVANTES_VENDAS',
    'TOTAL_BRUTO',
    'TOTAL_DESCONTO',
    'TOTAL_LIQUIDO'
    'VL_BRUTO_PREDATADO',
    'DESCONTO_PREDATADO',
    'LIQUIDO_PREDATADO',
    'TOTAL_REGISTROS_ARQUIVO'
]