COLUMNS = [
    'TIPO_REGISTRO',
    'NRO_FILIAL_MATRIZ',
    'QTDE_RESUMOS_VENDAS_ACATADOS',
    'QTDE_COMPROVANTES_VENDAS',
    'TOTAL_BRUTO',
    'TOTAL_DESCONTO',
    'TOTAL_LIQUIDO',
    'VL_BRUTO_PREDATADO',
    'DESCONTO_PREDATADO',
    'LIQUIDO_PREDATADO'
]