# Generated by Django 2.2.3 on 2019-07-30 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=250)),
                ('total_sql_queries', models.PositiveSmallIntegerField()),
                ('queries', models.TextField()),
                ('total_time', models.PositiveSmallIntegerField()),
                ('load_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
