# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoldp_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('chatConfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circles', to='djangoldp_account.ChatConfig')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_chatrooms', to=settings.AUTH_USER_MODEL)),
                ('team', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_circle', 'Read'), ('control_circle', 'Control')),
            },
        ),
    ]
