[build-system]
build-backend = "flit.buildapi"
requires=[
    "flit",
    "catt",
    "pyqt5",
    "pychromecast",
]
requires-python="3"
description-file="README.md"
[tool.flit.metadata]
module = "cattqt"
author = "Scott Moreau"
author-email = "oreaus@gmail.com"
home-page = "https://github.com/soreau/catt-qt"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

