version: '3'
services:

    http:
        build: .
        image: shuntingyard/speedtest_http
        restart: always
        ports:
          - "80:5000"
        volumes:
          - /data:/var/lib/speedtest
        environment:
          - FLASK_DEBUG=1
          - TZ=Europe/Zurich
          - SITENAME=Uplink green.ch
