# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 20:59
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openid_connect_op', '0003_openidclient_client_registration_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='openidclient',
            name='jwks',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
