# Generated by Django 2.1.5 on 2019-01-28 17:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openid_connect_op', '0009_auto_20190128_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidagreement',
            name='allowed_scopes',
            field=jsonfield.fields.JSONField(default=list, verbose_name='List of allowed scopes for this agreement.'),
        ),
    ]
