
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-16T11:54:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bf118f722068ff6c98a8252afcc1edeec03389c",
 "version": "1.8.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
