
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-07-30T08:33:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0319d766673ec56ef57eaad57340cff06840b843",
 "version": "v0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
