[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "expand"
author = "Marc Brooks"
author-email = "marcwbrooks@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

